kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: Deploy via SSH
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_user
      port: 2277
      ssh_key:
        from_secret: fivem-secret
      script:
        - cd /root/docker-fivem
        - ./start.sh
