kind: pipeline
type: docker
name: deploy

steps:
  - name: Deploy na VPS via SSH
    image: appleboy/drone-ssh
    settings:
      host: ntninfo.com.br.vps.yousecure.io    # Substitua pelo IP da sua VPS
      username: root                     # Ou "gitops", se usar outro usuário
      port: 2277
      key:
        from_secret: fivem-secret # Adicione no painel do DroneCI
      script:
        - cd /root/docker-fivem
        - chmod +x script.s
        - ./script.sh