kind: pipeline
type: docker
name: deploy

steps:
  - name: Deploy via SSH
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: deploy_user
      port: 2277
      ssh_key:
        from_secret: deploy_key
      script:
        - cd /root/docker-fivem
        - ./start.sh
