kind: pipeline
type: docker
name: deploy

steps:
  - name: Deploy na VPS via SSH
    image: appleboy/drone-ssh
    settings:
      host: ntninfo.com.br.vps.yousecure.io
      username: root
      port: 2277
      ssh_key:
        from_secret: fivem-secret
      script:
        - cd /root/docker-fivem
        - chmod +x start.sh
        - ./start.sh
